name: Testing
on:
  push:
    branches:
      - main
  pull_request: ~

jobs:
  phpunit:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/php-composer
      - name: PHPUnit
        run: php ./vendor/bin/phpunit -c ./phpunit.xml.dist
